name: Backend Microservices CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: 'us-east-2'
      ECR_REGISTRY: "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-2

      - name: Install Elastic Beanstalk CLI
        run: |
          pip install awsebcli --upgrade --user
          export PATH=$HOME/.local/bin:$PATH

      # Build and deploy discovery-server
      - name: Build and deploy discovery-server Docker image
        run: |
          docker buildx build --platform linux/amd64 -t kgalvan/discovery-server -f ./discovery-server/Dockerfile .
          cd ../discovery-server
          eb init --platform docker --region ${{ secrets.AWS_REGION }}
          eb use discovery-server-dev  
          eb deploy

      # Build and deploy api-gateway
      - name: Build and deploy api-gateway Docker image
        run: |
          docker buildx build --platform linux/amd64 -t kgalvan/api-gateway -f ./api-gateway/Dockerfile .
          cd ../api-gateway
          eb init --platform docker --region ${{ secrets.AWS_REGION }}
          eb use api-gateway-dev  
          eb deploy

      # Build and deploy user-service
      - name: Build and deploy user-service Docker image
        run: |
          docker buildx build --platform linux/amd64 -t kgalvan/user-service -f ./user-service/Dockerfile .
          cd ./user-service
          eb init --platform docker --region ${{ secrets.AWS_REGION }}
          eb use user-service-dev  
          eb deploy

      # Build and deploy game-service
      - name: Build and deploy game-service Docker image
        run: |
          docker buildx build --platform linux/amd64 -t kgalvan/game-service -f ./game-service/Dockerfile .
          cd ../game-service
          eb init --platform docker --region ${{ secrets.AWS_REGION }}
          eb use game-service-dev  
          eb deploy

      # Build and deploy review-service
      - name: Build and deploy review-service Docker image
        run: |
          docker buildx build --platform linux/amd64 -t kgalvan/review-service -f ./review-service/Dockerfile .
          cd ../review-service
          eb init --platform docker --region ${{ secrets.AWS_REGION }}
          eb use review-service-dev  
          eb deploy
